site.url=https://wildfly-security.github.io
quarkus.http.root-path=wildfly-elytron
quarkus.roq.tagging.lowercase=true

quarkus.qute.strict-rendering=true
quarkus.qute.property-not-found-strategy=noop

site.collections.blog=true

quarkus.asciidoc.attributes.icons=font
quarkus.asciidoc.attributes.source-highlighter=highlight.js
