---
layout: post
title:  "Welcome to Jekyll!"
date:   2020-01-02
tags: jekyll update
synopsis: This is a test.
author: fjuma
---
You’ll test find this post in your `_posts` directory. Go ahead and edit it and re-build the site to see your changes. You can rebuild the site in many different ways, but the most common way is to run `jekyll serve`, which launches a web server and auto-regenerates your site when a file is updated.

== Overview

To add new posts, simply add a file in the `_posts` directory that follows the convention `YYYY-MM-DD-name-of-post.ext` and includes the necessary front matter. Take a look at the source for this post to get an idea about how it works.

=== Syntax highlighting

Jekyll also offers powerful support for code snippets:

[source,shell]
puts "Hello, World!"

[source,java]
----
private void print(String s) {
   System.out.println(s);
}
----

=== Another section

This is a section. Blah Blah.
Test test test.

==== Another subsection


This is a section. Blah Blah.
Test test test.

== Summary

Check out the https://jekyllrb.com/docs/home[docs] for more info on how to get the most out of Jekyll.