<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The WildFly Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.wildfly.security</groupId>
        <artifactId>wildfly-elytron-parent</artifactId>
        <version>2.9.3.CR1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
     </parent>

    <packaging>pom</packaging>
    <artifactId>wildfly-elytron-bom-builder-all</artifactId>
    <name>WildFly Elytron BOM Builder: All</name>
    <description>This artifact builds a bill of materials (BOM), providing Dependency Management with all Elytron artifacts.</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-bom-builder-plugin</artifactId>
                <executions>
                    <execution>
                        <id>build-bom</id>
                        <goals>
                            <goal>build-bom</goal>
                        </goals>
                        <configuration>
                            <parent>
                                <groupId>org.jboss</groupId>
                                <artifactId>jboss-parent</artifactId>
                                <relativePath />
                            </parent>
                            <bomGroupId>org.wildfly.security</bomGroupId>
                            <bomArtifactId>wildfly-elytron-bom-all</bomArtifactId>
                            <bomVersion>${project.version}</bomVersion>
                            <bomName>WildFly Elytron BOM: All</bomName>
                            <bomDescription>Dependency Management with all Elytron modules</bomDescription>
                            <inheritExclusions>ALL</inheritExclusions>
                            <includeTransitives>false</includeTransitives>
                            <bomWithDependencies>true</bomWithDependencies>
                            <includeDependencies>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-asn1</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-audit</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-auth</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-auth-server</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-auth-server-deprecated</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-auth-server-http</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-auth-server-sasl</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-auth-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-base</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-client</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-credential</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-credential-source-deprecated</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-credential-source-impl</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-credential-store</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-digest</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-dynamic-ssl</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-encryption</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-basic</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-bearer</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-cert</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-deprecated</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-digest</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-external</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-form</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-oidc</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-spnego</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-sso</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-stateful-basic</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-http-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-json-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-jose-jwk</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-jose-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-keystore</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-mechanism</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-mechanism-digest</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-mechanism-gssapi</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-mechanism-http</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-mechanism-oauth2</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-mechanism-scram</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-password-impl</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-permission</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-provider-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-realm</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-realm-jdbc</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-realm-ldap</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-realm-token</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-anonymous</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-auth-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-deprecated</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-digest</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-entity</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-external</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-gs2</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-gssapi</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-localuser</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-oauth2</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-otp</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-plain</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-sasl-scram</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-security-manager</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-security-manager-action</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-ssl</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-ssh-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-tool</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-x500</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-x500-cert</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-x500-cert-acme</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-x500-cert-util</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-x500-deprecated</artifactId>
                                </dependency>
                                <dependency>
                                    <groupId>org.wildfly.security</groupId>
                                    <artifactId>wildfly-elytron-x500-principal</artifactId>
                                </dependency>
                            </includeDependencies>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <profiles>
        <!--
            Disable the parent pom's use of maven-gpg-plugin for these modules
            as it can't handle the fact we produce artifacts under multiple
            grouopIds; we need to use wildfly-maven-gpg-plugin to deal with signing.
        -->
        <profile>
            <id>central-release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>gpg-sign</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.wildfly</groupId>
                        <artifactId>wildfly-maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>gpg-sign</id>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <!--
                        The central-publishing-maven-plugin can't deal with this project's generated artifacts
                        because it writes maven-metadata-central-staging.xml files for those components that
                        Maven Central rejects.
                        So we hack this by redeclaring the central-publishing-maven-plugin
                        and then *after it* add a 'deploy' phase maven-clean-plugin execution to remove those files.-->
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <artifactId>maven-clean-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>post-stage-clean</id>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>clean</goal>
                                </goals>
                                <configuration>
                                    <excludeDefaultDirectories>true</excludeDefaultDirectories>
                                    <filesets>
                                        <fileset>
                                            <directory>${maven.multiModuleProjectDirectory}/target/central-staging</directory>
                                            <includes>
                                                <include>**/maven-metadata-*.xml</include>
                                            </includes>
                                        </fileset>
                                    </filesets>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
