name: Pull Request CI
on:
  pull_request:
    branches:
      - 2.x
      - 2.2.x
      - 2.6.x
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['17', '21', '25']
    steps:
      - name: Update hosts - linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cat /etc/hosts
          sudo bash -c "echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > /etc/hosts"
          sudo bash -c "echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> /etc/hosts"
          sudo sysctl -w fs.file-max=2097152
      - name: Update hosts - windows
        if: matrix.os == 'windows-latest'
        run: |
          type %SystemRoot%\System32\drivers\etc\hosts
          echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' >	%SystemRoot%\System32\drivers\etc\hosts
          echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> %SystemRoot%\System32\drivers\etc\hosts
        shell: cmd
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      # ELY-2204 - Temporarily preventing OidcTest from running on macOS since there
      # are intermittent issues with starting up the Docker container.
      #- if: matrix.os == 'macos-latest'
      #  name: Install docker
      #  run: |
      #    brew install docker docker-machine docker-compose
      #    brew services start docker-machine
      #    docker-machine create --driver virtualbox default
      #    docker --version
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ matrix.java }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-m2
      - name: Version Info
        run: mvn -version
        # Code for JDK versions < JDK-24 are incompatible with JDK-24+.
        # A (tmp) file flag is provided to demark the branch transition point.
      - name: Check for file existence
        id: file_check
        run: |
          if git ls-files --error-unmatch IsJdk24.txt > /dev/null 2>&1; then
            echo "file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "file_exists=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
      - name: Build with Maven branch JDK ${{ matrix.java }}  ${{ steps.file_check.outputs.file_exists }}
        if: steps.file_check.outputs.file_exists == 'false' && matrix.java < '24'
        run: mvn -B verify --file pom.xml
      - name: prototype testing for JDK ${{ matrix.java }} ${{ steps.file_check.outputs.file_exists }}
        if: steps.file_check.outputs.file_exists == 'true' && matrix.java >= '24'
        run: mvn -B verify --file pom.xml
      - name: debug data for env failure  (tmp step)
        if: ${{ failure() && ! contains(matrix.os, 'windows') }}
        shell: bash
        run: cat /etc/hosts;  ifconfig -a;

  elytron-web-build:
    name: Elytron Web Tests - JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        java: ['21']
    steps:
      - name: Update hosts
        run: |
          cat /etc/hosts
          sudo bash -c "echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > /etc/hosts"
          sudo bash -c "echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> /etc/hosts"
          sudo sysctl -w fs.file-max=2097152
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ matrix.java }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-m2
      - name: Version Info
        run: mvn -version
      - name: Install wildfly-elytron SNAPSHOT
        run: mvn -B install -DskipTests --file pom.xml
      - name: Get wildfly-elytron version
        id: elytron-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Clone Elytron Web
        run: git clone --depth 1 -b 4.x https://github.com/wildfly-security/elytron-web.git elytron-web
      - name: Build and test Elytron Web
        run: mvn -B verify -Dversion.org.wildfly.security.elytron=${{ steps.elytron-version.outputs.version }}
        working-directory: elytron-web
